#:import utils kivy.utils

<LoadingOverlay@BoxLayout>:
    canvas.before:
        Color:
            rgba: 0, 0, 0, 0.4
        Rectangle:
            pos: self.pos
            size: self.size
    AnchorLayout:
        anchor_x: 'center'
        anchor_y: 'center'
        BoxLayout:
            orientation: 'vertical'
            size_hint: None, None
            size: dp(120), dp(100)
            canvas.before:
                Color:
                    rgba: 1, 1, 1, 1
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [dp(15)]
            Label:
                text: 'Loading...'
                color: utils.get_color_from_hex('#0B8733')
                font_size: '16sp'
                bold: True
